# Associations between 16p11.2 and WBC using classical + drug covariates (individually)

#################################################
### Libraries ###################################
library(data.table)
library(dplyr)


#################################################
### STEP 1: Load data ###########################

# Genotypes; File is generated from 01_samples/01_sample_filtering.R
geno <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/02_CNV_carriers/data/final/16p11.2_CNV_profile_HC.txt", select = c(1,4)))

# Phenotypes INT and corrected by sex; File is generated from 04_phenotypes/01_phenotype_extraction.R 
pheno <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/04_phenotypes/data/final/INT_age_age2_batch_PCs/WBC_WB_INT_age_age2_sex_batch_PCs_All.txt", select = c(1,4,7)))

# Drug covariates; File is generated from 03_covariates/02_drug_covariates.R
drug <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/03_covariates/data/final/drug_covariates.txt"))

# Drug categories used by 16p11.2 deletion carriers; This file was generated by 02_CNV_carriers/02_drug_usage_CNV_carriers.R
cat <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/02_CNV_carriers/data/final/drug_usage/categories/drug_categories_1_DEL_carriers.txt", sep = "\t", header = F, col.names = "cat"))
print(paste0("Number of ATC drug categories used as covariates: ", length(cat$cat)))

# Description of ATC 3rd level; Generated from information on https://go.drugbank.com/atc
ATC <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/03_covariates/data/raw/ATC_3rd_level_210929.csv", col.names = c("ATC_DESCRIPTION", "ATC_CODE")))


#################################################
### STEP 2: Merge data ##########################

# Combine genotype and phenotype data
data <- left_join(geno, pheno, by = "eid")

# Select relevant ATC categoories
cat <- gsub(".*\\(", "", gsub(")", "", cat$cat))

# Add selected covariates to the data file
data <- left_join(data, drug[, c("eid", cat)], by = "eid")


#################################################
### STEP 3: Association studies #################

# Create an empty dataframe to store results of the linear regressions
lm_results <- data.frame()

# Counter
i <- 1

# Loop over phenotypes
for (p in c("lymphocyte_count", "neutrophil_count")) {

	# Loop over drugs
	for (d in cat) {

		# Create a temporary dataframe
		df <- data.frame(DEL = data$DEL, PHENO = residuals(lm(data[, p] ~ data[, d], na.action = na.exclude)))

		# Fit the linear regression		
		fit <- lm(df$PHENO ~ df$DEL, na.action = na.exclude)

		# Fill in the result table
		lm_results[i, "PHENO"] <- p
		lm_results[i, "ATC_CODE"] <- d
		lm_results[i, "ATC_DESCRIPTION"] <- ATC[which(ATC$ATC_CODE == d), "ATC_DESCRIPTION"]
		lm_results[i, "BETA"] <- summary(fit)$coefficients[2,1]
		lm_results[i, "SE"] <- summary(fit)$coefficients[2,2]
		lm_results[i, "t"] <- summary(fit)$coefficients[2,3]
		lm_results[i, "P"] <- summary(fit)$coefficients[2,4]

		# Increase the counter
		i <- i + 1
	}
}


#################################################
### Save ########################################

# Linear regression results
fwrite(lm_results[order(lm_results$P, decreasing = T), ], "/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/05_associations/data/final/drug_covariates/lm_results_16p11.2_WBC_drug_individual_covariates.txt", col.names = T, row.names = F, quote = F, sep = "\t")
