# Assess the expained variance by all drugs Vs. genotype (deletion)

#################################################
### Libraries ###################################
library(data.table)
library(tibble)
library(dplyr)


#################################################
### STEP 1: Load data ###########################

# Genotypes; File is generated from 01_samples/script/01_sample_filtering.
geno <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/02_CNV_carriers/data/final/16p11.2_CNV_profile_HC.txt", select = c(1,4)))

# Phenotypes INT and corrected by sex; File is generated from 04_phenotypes/script/01_phenotype_extraction.R 
pheno <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/04_phenotypes/data/final/INT_age_age2_batch_PCs/WBC_WB_INT_age_age2_sex_batch_PCs_All.txt", select = c(1,4,7,8)))

# Drug categories used by 16p11.2 deletion carriers; This file was generated by 02_CNV_carriers/script/02_drug_usage_CNV_carriers.R
cat <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/02_CNV_carriers/data/final/drug_usage/categories/drug_categories_1_DEL_carriers.txt", sep = "\t", header = F, col.names = "cat"))
cat <- gsub(".*\\(", "", gsub(")", "", cat$cat))
print(paste0("Number of ATC drug categories used as covariates: ", length(cat)))

# Drug covariates; File is generated from 03_covariates/script/02_drug_covariates.R
drug <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/03_covariates/data/final/drug_covariates.txt"))

# Description of ATC 3rd level; Generated from information on https://go.drugbank.com/atc
ATC <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/03_covariates/data/raw/ATC_3rd_level_210929.csv", col.names = c("ATC_DESCRIPTION", "ATC_CODE")))


#################################################
### STEP 2: Merge data ##########################

# Combine genotype and phenotype data
data <- left_join(geno, pheno, by = "eid")

# Add selected covariates to the data file
data <- left_join(data, drug[, c("eid", cat)], by = "eid")


#################################################
### STEP 3: Compare models ######################

# Create an empty dataframe to store (adj) R2 from the linear models
lm_results <- data.frame()

# Counter
i <- 1

# Loop over phenotypes
for (p in c("lymphocyte_count", "neutrophil_count", "basophil_count")) {

	# Model 1: residuals ~ geno
	df1 <- data[, c(p, "DEL")]
	colnames(df1)[1] <- "PHENO"
	fit1 <- lm(PHENO ~ DEL, data = df1, na.action = na.exclude)

	lm_results[i, "PHENO"] <- p
	lm_results[i, "MODEL"] <- "GENO"
	lm_results[i, "R2"] <- summary(fit1)$r.squared
	lm_results[i, "adjR2"] <- summary(fit1)$adj.r.squared

 	i <- i + 1
	

	# Model 2: residuals ~ drug1 + ... + drug55
	df2 <- data[, c(p, cat)]
	colnames(df2)[1] <- "PHENO"
	fit2 <- lm(PHENO ~ ., data = df2, na.action = na.exclude)

	lm_results[i, "PHENO"] <- p
	lm_results[i, "MODEL"] <- "DRUG"
	lm_results[i, "R2"] <- summary(fit2)$r.squared
	lm_results[i, "adjR2"] <- summary(fit2)$adj.r.squared

 	i <- i + 1


 	# Model 3: residuals ~ geno + drug1 + ... + drug55
	df3 <- data[, c(p, "DEL",cat)]
	colnames(df3)[1] <- "PHENO"
	fit3 <- lm(PHENO ~ ., data = df3, na.action = na.exclude)

	lm_results[i, "PHENO"] <- p
	lm_results[i, "MODEL"] <- "GENO_DRUG"
	lm_results[i, "R2"] <- summary(fit3)$r.squared
	lm_results[i, "adjR2"] <- summary(fit3)$adj.r.squared

	fit3_coeff <- as.data.frame(summary(fit3)$coefficients)
	fit3_coeff <- left_join(rownames_to_column(fit3_coeff), ATC, by = c("rowname" = "ATC_CODE"))

	fwrite(fit3_coeff, paste0("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/05_associations/data/final/model_comparison/full_model_", p,"_16p11.2_all.txt"), col.names = T, row.names = F, quote = F, sep = "\t")

 	i <- i + 1

}


#################################################
### Save ########################################

# Linear regression model fits
fwrite(lm_results, "/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/05_associations/data/final/model_comparison/model_comparison_covariates_16p11.2_WBC_all.txt", col.names = T, row.names = F, quote = F, sep = "\t")


