# Retrieve individuals with a 16p11.2 BP4-BP5 CNV among filtered individuals

#################################################
### Libraries ###################################
library(data.table)
library(dplyr)


#################################################
### Load Main Data ##############################

# Load selected samples; These files were generated by 01_samples/01_sample_filtering.R
all <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/01_samples/data/final/samples_white_british_All.txt", header = F, col.names = c("eid")))
males <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/01_samples/data/final/samples_white_british_M.txt", header = F, col.names = c("eid")))
females <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/01_samples/data/final/samples_white_british_F.txt", header = F, col.names = c("eid")))

# Load all CNVs; "ukb_cnv_global.gz" is the final PennCNV output, with all CNV calls in a linear format. Quality score was added by Mace et al., 2016's post-calling pipeline 
cnvs <- as.data.frame(fread("/home/cauwerx/scratch/cauwerx/projects/cnv_gwas/cnv_calls/final/ukb_cnv_global.gz"))
cnvs$Sample_Name <- sub("_.*", "", cnvs$Sample_Name)


#################################################
### STEP 1: Filter selected individual CNVs #####

# Retain samples among the list of retained individuals
cnvs <- cnvs[cnvs$Sample_Name %in% all$eid, ]

# Add sex information
cnvs[cnvs$Sample_Name %in% males$eid, "SEX"] <- "M"
cnvs[cnvs$Sample_Name %in% females$eid, "SEX"] <- "F"


#################################################
### STEP 2: Filter for CNV boundaries ###########

# Start: 29.4-29.8 Mb; End: 30.05-30.4 Mb

cnvs_16p11 <- cnvs[which(cnvs$Chromosome == 16 & cnvs$Start_Position_bp >= 29400000 & cnvs$Start_Position_bp <= 29800000 & cnvs$End_Position_bp >= 30050000 & cnvs$End_Position_bp <= 30400000), ]
print(paste0("Distribution of 16p11.2 BP4-BP5 CNV carriers (", nrow(cnvs_16p11),") by CN and sex:"))
print(table(cnvs_16p11$Copy_Number, cnvs_16p11$SEX))


#################################################
### STEP 3: Filter for QS #######################

# |QS| > 0.5
cnvs_16p11_HC <- cnvs_16p11[which(abs(cnvs_16p11$Quality_Score) >= 0.5), ]
print(paste0("Distribution of high confidence 16p11.2 BP4-BP5 CNV carriers (", nrow(cnvs_16p11_HC),") by CN and sex:"))
print(table(cnvs_16p11_HC$Copy_Number, cnvs_16p11_HC$SEX))


#################################################
### STEP 4: Combined table ######################

# Without QS filter
cnv_carriers <- all
cnv_carriers[cnv_carriers$eid %in% males$eid, "sex"] <- "M"
cnv_carriers[cnv_carriers$eid %in% females$eid, "sex"] <- "F"
cnv_carriers$DUP <- 0
cnv_carriers[cnv_carriers$eid %in% cnvs_16p11[which(cnvs_16p11$Copy_Number < 2), "Sample_Name"], "DUP"] <- NA
cnv_carriers[cnv_carriers$eid %in% cnvs_16p11[which(cnvs_16p11$Copy_Number > 2), "Sample_Name"], "DUP"] <- 1
cnv_carriers$DEL <- 0
cnv_carriers[cnv_carriers$eid %in% cnvs_16p11[which(cnvs_16p11$Copy_Number > 2), "Sample_Name"], "DEL"] <- NA
cnv_carriers[cnv_carriers$eid %in% cnvs_16p11[which(cnvs_16p11$Copy_Number < 2), "Sample_Name"], "DEL"] <- 1
cnv_carriers$MIRROR <- 0
cnv_carriers[which(cnv_carriers$DUP == 1), "MIRROR"] <- 1
cnv_carriers[which(cnv_carriers$DEL == 1), "MIRROR"] <- -1
cnv_carriers$U_SHAPE <- 0
cnv_carriers[which(cnv_carriers$DUP == 1 | cnv_carriers$DEL == 1), "U_SHAPE"] <- 1

# With QS filter
cnv_carriers_HC <- all
cnv_carriers_HC[cnv_carriers_HC$eid %in% males$eid, "sex"] <- "M"
cnv_carriers_HC[cnv_carriers_HC$eid %in% females$eid, "sex"] <- "F"
cnv_carriers_HC$DUP <- 0
cnv_carriers_HC[cnv_carriers_HC$eid %in% cnvs_16p11_HC[which(cnvs_16p11_HC$Copy_Number < 2), "Sample_Name"], "DUP"] <- NA
cnv_carriers_HC[cnv_carriers_HC$eid %in% cnvs_16p11_HC[which(cnvs_16p11_HC$Copy_Number > 2), "Sample_Name"], "DUP"] <- 1
cnv_carriers_HC$DEL <- 0
cnv_carriers_HC[cnv_carriers_HC$eid %in% cnvs_16p11_HC[which(cnvs_16p11_HC$Copy_Number > 2), "Sample_Name"], "DEL"] <- NA
cnv_carriers_HC[cnv_carriers_HC$eid %in% cnvs_16p11_HC[which(cnvs_16p11_HC$Copy_Number < 2), "Sample_Name"], "DEL"] <- 1
cnv_carriers_HC$MIRROR <- 0
cnv_carriers_HC[which(cnv_carriers_HC$DUP == 1), "MIRROR"] <- 1
cnv_carriers_HC[which(cnv_carriers_HC$DEL == 1), "MIRROR"] <- -1
cnv_carriers_HC$U_SHAPE <- 0
cnv_carriers_HC[which(cnv_carriers_HC$DUP == 1 | cnv_carriers_HC$DEL == 1), "U_SHAPE"] <- 1


#################################################
### Save ########################################

# CNV carriers profiles
fwrite(cnv_carriers, "/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/02_CNV_carriers/data/final/16p11.2_CNV_profile.txt", row.names = F, col.names = T, quote = F, sep = "\t")
fwrite(cnv_carriers_HC, "/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/02_CNV_carriers/data/final/16p11.2_CNV_profile_HC.txt", row.names = F, col.names = T, quote = F, sep = "\t")

# CNV carriers coordinates
fwrite(cnvs_16p11, "/home/cauwerx/scratch/cauwerx/projects/COLLABORATION/Giuliana/16p11.2_wbc/02_CNV_carriers/data/final/16p11.2_CNV_coordinates.txt", row.names = F, col.names = T, quote = F, sep = "\t")
